all: AtomicCounters BasicDebug BinarySearch BinomialOption BinomialOptionMultiGPU BitonicSort BlackScholes BlackScholesDP BoxFilter BoxFilterGL BufferBandwidth BufferImageInterop DCT DeviceFission DeviceFission11Ext DwtHaar1D DynamicOpenCLDetection FastWalshTransform FloydWarshall FluidSimulation2D GaussianNoiseGL HelloWorld Histogram ImageBandwidth ImageOverlap KernelLaunch KmeansAutoclustering LUDecomposition Mandelbrot MatrixMulImage MatrixMultiplication MatrixTranspose MemoryModel MonteCarloAsian MonteCarloAsianDP MonteCarloAsianMultiGPU NBody PrefixSum QuasiRandomSequence RadixSort RecursiveGaussian Reduction ScanLargeArrays SimpleConvolution SimpleGL SimpleImage SimpleMultiDevice SobelFilter StringSearch Template TransferOverlap URNG

AtomicCounters:
	cd AtomicCounters && make

BasicDebug:
	cd BasicDebug && make

BinarySearch:
	cd BinarySearch && make

BinomialOption:
	cd BinomialOption && make

BinomialOptionMultiGPU:
	cd BinomialOptionMultiGPU && make

BitonicSort:
	cd BitonicSort && make

BlackScholes:
	cd BlackScholes && make

BlackScholesDP:
	cd BlackScholesDP && make

BoxFilter:
	cd BoxFilter && make

BoxFilterGL:
	cd BoxFilterGL && make

BufferBandwidth:
	cd BufferBandwidth && make

BufferImageInterop:
	cd BufferImageInterop && make

DCT:
	cd DCT && make

DeviceFission:
	cd DeviceFission && make

DeviceFission11Ext:
	cd DeviceFission11Ext && make

DwtHaar1D:
	cd DwtHaar1D && make

DynamicOpenCLDetection:
	cd DynamicOpenCLDetection && make

FastWalshTransform:
	cd FastWalshTransform && make

FloydWarshall:
	cd FloydWarshall && make

FluidSimulation2D:
	cd FluidSimulation2D && make

GaussianNoiseGL:
	cd GaussianNoiseGL && make

HelloWorld:
	cd HelloWorld && make

Histogram:
	cd Histogram && make

ImageBandwidth:
	cd ImageBandwidth && make

ImageOverlap:
	cd ImageOverlap && make

KernelLaunch:
	cd KernelLaunch && make

KmeansAutoclustering:
	cd KmeansAutoclustering && make

LUDecomposition:
	cd LUDecomposition && make

Mandelbrot:
	cd Mandelbrot && make

MatrixMulImage:
	cd MatrixMulImage && make

MatrixMultiplication:
	cd MatrixMultiplication && make

MatrixTranspose:
	cd MatrixTranspose && make

MemoryModel:
	cd MemoryModel && make

MonteCarloAsian:
	cd MonteCarloAsian && make

MonteCarloAsianDP:
	cd MonteCarloAsianDP && make

MonteCarloAsianMultiGPU:
	cd MonteCarloAsianMultiGPU && make

NBody:
	cd NBody && make

PrefixSum:
	cd PrefixSum && make

QuasiRandomSequence:
	cd QuasiRandomSequence && make

RadixSort:
	cd RadixSort && make

RecursiveGaussian:
	cd RecursiveGaussian && make

Reduction:
	cd Reduction && make

ScanLargeArrays:
	cd ScanLargeArrays && make

SimpleConvolution:
	cd SimpleConvolution && make

SimpleGL:
	cd SimpleGL && make

SimpleImage:
	cd SimpleImage && make

SimpleMultiDevice:
	cd SimpleMultiDevice && make

SobelFilter:
	cd SobelFilter && make

StringSearch:
	cd StringSearch && make

Template:
	cd Template && make

TransferOverlap:
	cd TransferOverlap && make

URNG:
	cd URNG && make

